apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pollu-escape-temp
  name: pollu-escape-temp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pollu-escape-temp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pollu-escape-temp
    spec:
      containers:
      - image: polluescapeazurecontainerregistry.azurecr.io/map-temp:v0.2.3
        name: map-temp
        resources: {}
status: {}