# Generated by Django 3.2 on 2021-05-11 02:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('map_utils', '0002_datapoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='time_taken',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
