# Generated by Django 3.2 on 2021-05-11 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_utils', '0003_datapoint_time_taken'),
    ]

    operations = [
        migrations.CreateModel(
            name='jsonFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_time', models.DateTimeField()),
                ('jsonString', models.TextField()),
            ],
        ),
    ]
