# Generated by Django 3.2 on 2021-05-11 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_utils', '0007_remove_datapoint_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsonfeature',
            name='processed_time',
        ),
    ]
