# Generated by Django 3.2 on 2021-05-11 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_utils', '0008_remove_jsonfeature_processed_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapoint',
            name='time_taken',
        ),
    ]
