# Generated by Django 3.2 on 2021-05-11 02:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('map_utils', '0009_remove_datapoint_time_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='time_taken',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jsonfeature',
            name='processed_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
