# Generated by Django 3.2 on 2021-05-12 01:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('map_utils', '0011_alter_jsonfeature_processed_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonfeature',
            name='time_taken',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
